/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-11-19 13:24:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.DB.connection.Connect;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "&lt;%@page import=\"java.sql.Connection\"%&gt;";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.DB.connection.Connect");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  	 
		if(request.getSession().getAttribute("empid")==null)
        {      request.getRequestDispatcher("index.jsp").forward(request, response);   
           }else{
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Classic</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://maps.google.com/maps/api/js?sensor=false\"\r\n");
      out.write("></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"js/Map.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>  \r\n");
      out.write("var request;  \r\n");
      out.write("function sendInfo()  \r\n");
      out.write("{  \r\n");
      out.write("var v=document.vform.Capacity.value;  \r\n");
      out.write("var url=\"ajax.jsp?val=\"+v;  \r\n");
      out.write("  \r\n");
      out.write("if(window.XMLHttpRequest){  \r\n");
      out.write("request=new XMLHttpRequest();  \r\n");
      out.write("}  \r\n");
      out.write("else if(window.ActiveXObject){  \r\n");
      out.write("request=new ActiveXObject(\"Microsoft.XMLHTTP\");  \r\n");
      out.write("}  \r\n");
      out.write("  \r\n");
      out.write("try  \r\n");
      out.write("{  \r\n");
      out.write("request.onreadystatechange=getInfo;  \r\n");
      out.write("request.open(\"GET\",url,true);  \r\n");
      out.write("request.send();  \r\n");
      out.write("}  \r\n");
      out.write("catch(e)  \r\n");
      out.write("{  \r\n");
      out.write("document.getElementById('tab').innerHTML=\"Unable to connect to server\";  \r\n");
      out.write("}  \r\n");
      out.write("}  \r\n");
      out.write("  \r\n");
      out.write("function getInfo(){  \r\n");
      out.write("if(request.readyState==4){  \r\n");
      out.write("var val=request.responseText;  \r\n");
      out.write("document.getElementById('tab').innerHTML=val; \r\n");
      out.write("document.getElementById(\"map_canvas\").style.height='83%';\r\n");
      out.write("document.getElementById(\"tab\").style.visibility=\"visible\"; \r\n");
      out.write("}  \r\n");
      out.write("}  \r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\" class=\"panel-body\">\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1 align=\"center\"><img src=\"./images/logo.jpg\" alt=\"Logo\"></h1>\r\n");
      out.write("\t\t<p style=\"text-align: left;\">\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminAuto.jsp\">Auto</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"admin.jsp\">Classic</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminAdvanced.jsp\">Advanced</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\" class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"\r\n");
      out.write("\t\t\t\t>Control Panel<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminCapex.jsp\">Capex</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminfixed.jsp\">Fixed Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminvariable.jsp\">Variable Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"admintrip.jsp\">Trip Matrix</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"locations.jsp\">Locations</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminUploadFreight.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tFreight</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminUploadContract.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tContract</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"UserSession.jsp\">User Record</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t<div id=\"map_canvas\" class=\"right panel-body embed-responsive-item\"\r\n");
      out.write("\t\t\tstyle=\"height: 19%\"\r\n");
      out.write("\t\t></div>\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<h5 class=\"panel-header\" style=\"font-weight: bold; padding: 1%\">Classic</h5>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<form method=\"Post\" action=\"Basic\" class=\"form-group panel-body\"\r\n");
      out.write("\t\t\t\tname=\"vform\"\r\n");
      out.write("\t\t\t>\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"start\" id=\"start\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Origin\" onchange=\"calcRoute()\"\r\n");
      out.write("\t\t\t\t\t\t\trequired\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"end\" id=\"end\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Destination\"\r\n");
      out.write("\t\t\t\t\t\t\tonchange=\"calcRoute()\" required\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"back\" id=\"back\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Backhaul %\" size=\"3\" maxlength=\"3\" required\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select name='Capacity' class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tonchange=\"sendInfo()\" id=\"dropDownId\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							int empid=(int)session.getAttribute("empid");
							 String sql = "select typeofgood,capacity from truckparam order by capacity";
			 
							try{ 
							 Connection con = Connect.getconnection();
							 PreparedStatement ps=con.prepareStatement(sql);					 		 
					 		 ResultSet rs = ps.executeQuery();
					               while( rs.next() )
					 		 {
							 	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='");
      out.print(rs.getString("typeofgood") );
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname='typeofgood' class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>");
      out.print(rs.getString("typeofgood") );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

					 		}
			
					            	
				}
				catch(Exception e){
					e.printStackTrace();
					RequestDispatcher ReqDis = request.getRequestDispatcher("Adminerror.jsp");
				ReqDis.forward(request, response);
				}
		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"hidden\" name=\"distance\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"distance\"\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("empid"));
      out.write("' name=\"empid\"\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Submit\" disabled=\"true\" id=\"mySubmit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdocument.getElementById(\"dropDownId\").addEventListener(\"load\", initialize());\r\n");
      out.write("\t\t\tdocument.getElementById(\"dropDownId\").addEventListener(\"load\", sendInfo());\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<label id=\"1234\"></label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"login-card table-responsive table table-bordered table-condensed tabel-hover\"\r\n");
      out.write("\t\t\tid=\"tab\" style=\"visibility: hidden;\"\r\n");
      out.write("\t\t></div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<div class=\"panel-body\"></div>\r\n");
      out.write("\t\t<footer class=\"panel-footer\"\r\n");
      out.write("\t\t\tstyle=\" bottom:2%; text-align:center; color:white;position:  relative; \"\r\n");
      out.write("\t\t> Copyright &copy McKinsey & Company</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
