/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-11-19 14:06:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.DB.connection.Connect;

public final class adminvariable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.DB.connection.Connect");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  	 
		if(request.getSession().getAttribute("empid")==null)
        {      request.getRequestDispatcher("index.jsp").forward(request, response);   
           }else{
           try{			
           				String truckType=(String)session.getAttribute("truckType");
           				int cap=(int)session.getAttribute("cap");
						int cost=(int)session.getAttribute("cost");
						float residual=(float)session.getAttribute("residual");
						float loan=(float)session.getAttribute("loan");
						int emi=(int)session.getAttribute("emi");
						float roi=(float)session.getAttribute("roi");
						float flatroi=(float)session.getAttribute("flatroi");
						//System.out.print(truckType);
						
						String trucktype1=(String)request.getParameter("truckType");
						int sal=Integer.parseInt(request.getParameter("salary" ));
						int bhatta=Integer.parseInt(request.getParameter("bhatta" ));
						int main=Integer.parseInt(request.getParameter("main" ));
						int roadtax=Integer.parseInt(request.getParameter("roadtax" ));
						int permit=Integer.parseInt(request.getParameter("permit"));
						float insurance=Float.parseFloat(request.getParameter("insurance"));
						int admin=Integer.parseInt(request.getParameter("admin"));
						int tarpaulin=Integer.parseInt(request.getParameter("tarpaulin"));
						int profit=Integer.parseInt(request.getParameter("profit"));
						int loading=Integer.parseInt(request.getParameter("loading"));
						//System.out.print(trucktype1);
						
						if(truckType.equals(trucktype1)){
						
						session.setAttribute("truckType", truckType);
						session.setAttribute("cap", cap);
						session.setAttribute("cost", cost);
						session.setAttribute("residual", residual);
						session.setAttribute("loan", loan);
						session.setAttribute("emi", emi);
						session.setAttribute("roi", roi);
						session.setAttribute("flatroi", flatroi);
												
						session.setAttribute("sal", sal);
						session.setAttribute("bhatta", bhatta);
						session.setAttribute("main", main);
						session.setAttribute("roadtax", roadtax);
						session.setAttribute("permit", permit);
						session.setAttribute("insurance", insurance);
						session.setAttribute("admin", admin);
						session.setAttribute("tarpaulin", tarpaulin);
						session.setAttribute("loading", loading);
						session.setAttribute("profit", profit);
						
					}else{
					RequestDispatcher rd= request.getRequestDispatcher("Adminerror.jsp");
					rd.forward(request, response);
					}					
						
						
						
           }catch(Exception e){e.printStackTrace();
           }
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<title>Variable Cost</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function myFunction() {\r\n");
      out.write("    location.reload();\r\n");
      out.write("}\r\n");
      out.write("function clickadd()\r\n");
      out.write("{\r\n");
      out.write("document.getElementById('add').style.visibility = 'hidden';\r\n");
      out.write("\r\n");
      out.write("document.getElementById('modify').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('refresh').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('1').style.visibility = 'visible';\r\n");
      out.write("document.getElementById('2').style.visibility = 'visible';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"panel-body\">\r\n");
      out.write("\t");
String name = request.getParameter( "name" );
	 
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1 align=\"center\"><img src=\"./images/logo.jpg\" alt=\"Logo\"></h1>\r\n");
      out.write("\t\t<p style=\"text-align: left;\">\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminAuto.jsp\">Auto</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"admin.jsp\">Classic</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminAdvanced.jsp\">Advanced</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\" class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"\r\n");
      out.write("\t\t\t\t>Control Panel<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminCapex.jsp\">Capex</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminfixed.jsp\">Fixed Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminvariable.jsp\">Variable Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"admintrip.jsp\">Trip Matrix</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"locations.jsp\">Locations</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminUploadFreight.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tFreight</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"adminUploadContract.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tContract</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"UserSession.jsp\">User Record</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section style=\"width:100%\">\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<h2 align=\"center\">Control Panel</h2>\r\n");
      out.write("\t\t\t<form action=\"Param\" method=\"post\">\r\n");
      out.write("\t\t\t\t<h2 align=\"center\">Variable Cost</h2>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-hover table-condensed\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Truck Type</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tyre life (Km)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tyre life (Retredded tyre) (Km)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tyre Cost (INR)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tyre Cost (Retredded tyre) (INR)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>No. of tyres</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Diesel Cost</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Diesel Milage Km/L</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Diesel Mileage (With Load) Km/L</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Toll per km</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Route expenses per km</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Maintanence cost per km</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t");

			int empid=(int)session.getAttribute("empid");
		 	String sql = "select * from  mckc.truckparam t, mckc.routeparam r where  r.typeofgood=t.typeofgood GROUP BY t.capacity,r.capacity HAVING COUNT(*) > 0  order by t.capacity";
			 
				try{ 
							 Connection con = Connect.getconnection();
							 PreparedStatement ps=con.prepareStatement(sql);					 		 
					 		 ResultSet rs = ps.executeQuery();
					               while( rs.next() )
					 		 {
							 	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getString("typeofgood"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getInt("tyrelife"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getInt("reusedtyrelife"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getInt("tyrecost"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getInt("reusedtyrecost"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getInt("tyres"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("dieselcost"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("dieselmileage"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("diesealmileagewithload"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("toll"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("routeexpenses"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue='");
      out.print(rs.getFloat("maintenancecostperkm"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t");

					 		}
			
					            	
				}
				catch(Exception e){
					e.printStackTrace();
					RequestDispatcher ReqDis = request.getRequestDispatcher("Adminerror.jsp");
				ReqDis.forward(request, response);
				}
		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=1 style=\"visibility: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"truckType\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"tyrelife\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"resusedtyrelife\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"tyrecost\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"reusedtyrecost\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"tyres\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"diesel\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"mileage\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"mileageload\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"toll\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"routeexpense\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"maintkm\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><input type=\"button\" value=\"Add\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"add\" id=\"add\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"clickadd()\"\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><a href=\"modifyvar.jsp\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"button\" value=\"Modify\" name=\"modify\" id=\"modify\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><input type=\"button\" value=\"Refresh\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"refresh\" id=\"refresh\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"myFunction()\"\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"2\" style=\"visibility: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value='");
      out.print(session.getAttribute("empid"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"empid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t> <input type=\"submit\" name=\"submit\" value=\"Submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction()\" value=\"Cancel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<div class=\"panel-body\"></div>\r\n");
      out.write("\t\t<footer class=\"panel-footer\"\r\n");
      out.write("\t\t\tstyle=\" bottom:2%; text-align:center; color:white;position:  relative; \"\r\n");
      out.write("\t\t> Copyright &copy McKinsey & Company</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
