/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-10-12 13:05:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>CleanSheet Admin Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/homestyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\">\r\n");
      out.write("\t");
String name = request.getParameter( "name" );
	 
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1>CLEANSHEET</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<nav> <a href=\"admin.jsp\">Basic</a> <br>\r\n");
      out.write("\t\t<a href=\"adminAdvanced.jsp\">Advanced</a> <br>\r\n");
      out.write("\t\t<a href=\"adminAuto.jsp\">Auto</a> <br>\r\n");
      out.write("\t\t<a href=\"adminParam.jsp\">Parameter Master</a> <br>\r\n");
      out.write("\t\t<a href=\"adminUploadFreight.jsp\">Upload Freight</a> <br>\r\n");
      out.write("\t\t<a href=\"adminUploadContract.jsp\">Upload Contract</a> <br>\r\n");
      out.write("\t\t<a href=\"UserSession.jsp\">User Session</a> <br>\r\n");
      out.write("\t\t<a href=\"editTable.jsp\">Edit Table</a> <br>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section style=\"width:79%; overflow: auto;\">\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<h2>Edit Table</h2>\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Capacity (tons)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Cost of Truck (INR)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Distance travelled per month (km)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Residual value of the truck at end of EMI (%)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Loan amount(%)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>No. of years of EMI payment</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Rate of Interest (%)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Insurance as percentage of vehicle cost (% p.a.)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tyre life (Km)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tyre life (Retredded tyre) (Km)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tyre Cost (INR)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tyre Cost (Retreading) (INR)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>No. of tyres</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Diesel cost Rs/L Diesel Mileage (With Load) Km/L</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Driver/Cleaner monthly salary</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Driver/Cleaner monthly bhatta</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Maintenace (per month)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Road tax per month (including fitness)</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Road permit per month</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Admin Costs</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tarpaulin</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Profit margin</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Toll per km</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Route expenses per km</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Maintanence cost per km</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
 for(int j=0; j<10; j++)
						{
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><select name='Capacity'>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
for(int i=9;i<34;i++)
						{
							out.write("<option value="+i+" name="+i+">"+i+"</option><br>");
						
						} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"cost\" size=\"7\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"distance\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"residual\" size=\"3\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"loan\" size=\"3\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"emi\" size=\"2\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"roi\" size=\"3\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"newtyre\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"oldtyre\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"newtyrecost\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"oldtyrecost\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"notyre\" size=\"3\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"mileage\" size=\"2\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"salary\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"bhatta\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"maintenace\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"roadtax\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"roadpermit\" size=\"5\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"admincost\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"tarpaulin\" size=\"2\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"profit\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"toll\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"routeexpences\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"maintanecekm\" size=\"4\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"25\"><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"Update\" class=\"login login-submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Update\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<footer style=\"position: relative;\"> Copyright © McKinsey &\r\n");
      out.write("\t\tCompany </footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
