/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-10-14 11:41:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class location_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>AUTO</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://maps.google.com/maps/api/js?sensor=false\"\r\n");
      out.write("></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"js/Map.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/latlong1.js\"\r\n");
      out.write("></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/homestyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\">\r\n");
      out.write("\t");
String name = request.getParameter( "name" );
	 
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1>CLEANSHEET</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<nav> <a href=\"Auto.jsp\">Auto</a> <br>\r\n");
      out.write("\t\t<a href=\"home.jsp\">Classic</a> <br>\r\n");
      out.write("\t\t<a href=\"Advanced.jsp\">Advanced</a> <br>\r\n");
      out.write("\t\t<a href=\"Param.jsp\">Control Panel</a> <br>\r\n");
      out.write("\t\t<a href=\"uploadFreight.jsp\">Upload Freight</a> <br>\r\n");
      out.write("\t\t<a href=\"uploadContract.jsp\">Upload Contract</a> <br>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section style=\"width:79%\">\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<h2>NearBy Locations</h2>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<form action=\"Auto\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table align=\"center\" style=\"width: 35%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
String origin=(String)session.getAttribute("backstart");
					
					 
      out.write("NearBy locations are :\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select name=\"backstart\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle='font-family: Palatino Linotype' required\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
// for(int i=0;i<(int)session.getAttribute("i");i++)
						{
							out.write("<option value="+origin+" name='backstart' style='font-family:Palatino Linotype'>"+origin+"</option><br>");
						
						} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"hidden\" name=\"start\" id=\"start\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("start"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\" name=\"end\" id=\"end\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("end"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\" name=\"distance\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("distance"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\" name=\"Capacity\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("cap"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\" name=\"back\" value=\"100\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"good\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("good"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("empid"));
      out.write("' name=\"empid\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" class=\"login login-submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t\t<footer style=\"position:  relative;\"> Copyright © McKinsey &\r\n");
      out.write("\t\tCompany </footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
