/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-11-05 10:41:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.DB.connection.Connect;

public final class Auto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  	 
		if(request.getSession().getAttribute("empid")==null)
        {      request.getRequestDispatcher("index.jsp").forward(request, response);   
           }else{
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>AUTO</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://maps.google.com/maps/api/js?sensor=false\"\r\n");
      out.write("></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/latlong1.js\"\r\n");
      out.write("></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"js/Map.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\" class=\"panel-body\">\r\n");
      out.write("\t");
String name = request.getParameter( "name" );
	 
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1 align=\"center\">TRAC- Transport Cleansheet Costing Tool</h1>\r\n");
      out.write("\t\t<p style=\"text-align: left;\">\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"Auto.jsp\">Auto</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"home.jsp\">Classic</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"Advanced.jsp\">Advanced</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\" class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"\r\n");
      out.write("\t\t\t\t>Control Panel<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"Capex.jsp\">Capex</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"fixed.jsp\">Fixed Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"variable.jsp\">Variable Cost</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"trip.jsp\">Trip Matrix</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"uploadFreight.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tFreight</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"uploadContract.jsp\">Upload\r\n");
      out.write("\t\t\t\t\t\tContract</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section class=\"container-fluid\">\r\n");
      out.write("\t\t<div id=\"map_canvas\" class=\"right panel-body\" style=\"height: 85%\"></div>\r\n");
      out.write("\t\t<div class=\"login-card \">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<h5 class=\"panel-header\">Auto</h5>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<form action=\"Loc\" method=\"post\" class=\"form-group panel-body\">\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"start\" id=\"start\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Origin\" onchange=\"calcRoute()\" required\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"end\" id=\"end\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Destination\" onblur=\"calcLat()\"\r\n");
      out.write("\t\t\t\t\t\t\tonchange=\"calcRoute()\" required class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select name='Capacity' class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							int empid=(int)session.getAttribute("empid");
							 String sql = "select typeofgood,capacity from truckparam order by capacity";
			 
							try{ 
							 Connection con = Connect.getconnection();
							 PreparedStatement ps=con.prepareStatement(sql);					 		 
					 		 ResultSet rs = ps.executeQuery();
					               while( rs.next())
					 		 {
							 	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='");
      out.print(rs.getString("typeofgood") );
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname='typeofgood'\r\n");
      out.write("\t\t\t\t\t\t\t\t>");
      out.print(rs.getString("typeofgood") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

					 		}					            	
				}
				catch(Exception e){
					e.printStackTrace();
					RequestDispatcher ReqDis = request.getRequestDispatcher("error.jsp");
				ReqDis.forward(request, response);
				}
		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"hidden\" name=\"distance\" id=\"distance\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"lat\" id=\"lat\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"long\" id=\"long\"\r\n");
      out.write("\t\t\t\t\t\t> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      out.print(session.getAttribute("empid"));
      out.write("' name=\"empid\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login login-submit btn btn-primary active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Submit\" disabled=\"true\" id=\"mySubmit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<label id=\"1234\"></label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div  class=\"login-card table-responsive\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"2\">CAPEX\r\n");
      out.write("\t\t\t</th></tr>\r\n");
      out.write("\t\t\t");
 String cap=request.getParameter("Capacity");
			String sql1 = "select * from truckparam t, routeparam r where t.typeofgood=r.typeofgood and t.typeofgood="+cap;
			 			
							try{ 
							 Connection con = Connect.getconnection();
							 PreparedStatement ps1=con.prepareStatement(sql1);					 		 
					 		 ResultSet rs1 = ps1.executeQuery();
					               while( rs1.next())
					 		 {
			
      out.write("<tr>\r\n");
      out.write("\t\t\t<th>Cost of truck:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("costoftruck") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Capacity:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("capacity") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Rate of interest:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getFloat("rateofintrest") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"2\">Fixed Cost\r\n");
      out.write("\t\t\t</th></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Driver Salary:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("`driver/cleaner salary`") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Maintenance(per month):</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("maintenancepermonth") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Road tax(per year):</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("roadtaxyear") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Road permit(per year):</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("roadpermityear") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Admin Cost:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("admin costs") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"2\">Variable Cost\r\n");
      out.write("\t\t\t</th></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Diesel Cost:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("dieselcost") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Tyre Cost:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("tyrecost") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Tyre life:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("tyrelife") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Mileage with load per km:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("diesealmileagewithload") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Route Expense per km:</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs1.getInt("routeexpenses") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} }
				catch(Exception e){
					e.printStackTrace();
					RequestDispatcher ReqDis = request.getRequestDispatcher("error.jsp");
				ReqDis.forward(request, response);
				}
      out.write("\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<div  class=\"panel-body\"></div>\r\n");
      out.write("\t\t<footer class=\"panel-footer\"\r\n");
      out.write("\t\t\tstyle=\" bottom:2%; text-align:center; color:white;position:relative; \"\r\n");
      out.write("\t\t> Copyright &copy McKinsey & Company</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
