/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-10-15 11:14:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.NumberFormat;
import java.text.DecimalFormat;

public final class detailsBasic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Home Page</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://maps.google.com/maps/api/js?sensor=false\"\r\n");
      out.write("></script>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"./css/styles.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"./js/amcharts.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"./js/serial.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"js/Map.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/homestyle.css\">\r\n");
      out.write(" <script>\r\n");
      out.write("\t\t\tvar Depreciation=");
      out.print(session.getAttribute("dep") );
      out.write("; \r\n");
      out.write("\t\t\tvar Interest=");
      out.print(session.getAttribute("intres") );
      out.write("; \t\t\t\t\r\n");
      out.write("\t\t\tvar Salary=");
      out.print(session.getAttribute("salr") );
      out.write(";\r\n");
      out.write("\t\t\tvar cost=0;\r\n");
      out.write("\t\t\tvar Insurance=");
      out.print(session.getAttribute("insu") );
      out.write(";\r\n");
      out.write("\t\t\tvar Roadtax=");
      out.print(session.getAttribute("rota") );
      out.write(";\r\n");
      out.write("\t\t\tvar Others=0;\r\n");
      out.write("\t\t\tvar Total=Depreciation+Interest+Salary+cost+Insurance+Roadtax+Others;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar Diesel=");
      out.print(session.getAttribute("dies") );
      out.write(";\r\n");
      out.write("\t\t\tvar toll=");
      out.print(session.getAttribute("tole") );
      out.write(";\r\n");
      out.write("\t\t\tvar tyre=");
      out.print(session.getAttribute("tyres") );
      out.write(";\r\n");
      out.write("\t\t\tvar\troute=");
      out.print(session.getAttribute("routes") );
      out.write(";\r\n");
      out.write("\t\t\tvar cost=");
      out.print(session.getAttribute("maint") );
      out.write(";\r\n");
      out.write("\t\t\tvar total1=Diesel+toll+tyre+route+cost;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar chart, chart1;\r\n");
      out.write("            \r\n");
      out.write("\t\t\tvar chartData = [\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Depre<br>ciation\",\r\n");
      out.write("                    \"open\": 0,\r\n");
      out.write("                    \"close\": Depreciation,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Depreciation\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Interest<br>Cost\",\r\n");
      out.write("                    \"open\": Depreciation,\r\n");
      out.write("                    \"close\":Depreciation+Interest,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Interest\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Driver/<br>Cleaner<br>Salary\",\r\n");
      out.write("                    \"open\":Depreciation+Interest,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Salary\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Total<br>Cost\",\r\n");
      out.write("                    \"open\": Depreciation+Interest+Salary,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary+cost,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": cost\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Insurance\",\r\n");
      out.write("                    \"open\": Depreciation+Interest+Salary+cost,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary+cost+Insurance,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Insurance\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Road<br>Tax<br>(Including<br>Fitness)\",\r\n");
      out.write("                    \"open\": Depreciation+Interest+Salary+cost+Insurance,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary+cost+Insurance+Roadtax,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Roadtax\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Others\",\r\n");
      out.write("                    \"open\": Depreciation+Interest+Salary+cost+Insurance+Roadtax,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary+cost+Insurance+Roadtax+Others,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Others\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Total\",\r\n");
      out.write("                    \"open\": 0,\r\n");
      out.write("                    \"close\": Depreciation+Interest+Salary+cost+Insurance+Roadtax+Others,\r\n");
      out.write("                    \"color\": \"#1A237E\",\r\n");
      out.write("                    \"balloonValue\": Total\r\n");
      out.write("                },\r\n");
      out.write("            ];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar chartD = [\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Diesel<br>Cost\",\r\n");
      out.write("                    \"open\": 0,\r\n");
      out.write("                    \"close\": Diesel,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": Diesel\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Toll<br>expenses\",\r\n");
      out.write("                    \"open\": Diesel,\r\n");
      out.write("                    \"close\":Diesel+toll,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": toll\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Tyre<br>Cost\",\r\n");
      out.write("                    \"open\":Diesel+toll,\r\n");
      out.write("                    \"close\": Diesel+toll+tyre,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": tyre\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"name\": \"Route<br>Expenses\",\r\n");
      out.write("                    \"open\": Diesel+toll+tyre,\r\n");
      out.write("                    \"close\": Diesel+toll+tyre+route,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": route\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Maintanence<br>Cost\",\r\n");
      out.write("                    \"open\": Diesel+toll+tyre+route,\r\n");
      out.write("                    \"close\": Diesel+toll+tyre+route+cost,\r\n");
      out.write("                    \"color\": \"#0D47A1\",\r\n");
      out.write("                    \"balloonValue\": cost\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("                    \"name\": \"Total\",\r\n");
      out.write("                    \"open\": 0,\r\n");
      out.write("                    \"close\": Diesel+toll+tyre+route+cost,\r\n");
      out.write("                    \"color\": \"#1A237E\",\r\n");
      out.write("                    \"balloonValue\": total1\r\n");
      out.write("                },\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("            AmCharts.ready(function () {\r\n");
      out.write("                // Waterfall chart is a simple serial chart with some specific settings\r\n");
      out.write("                chart = new AmCharts.AmSerialChart();\r\n");
      out.write("                chart.dataProvider = chartData;\r\n");
      out.write("                chart.categoryField = \"name\";\r\n");
      out.write("                chart.columnWidth = .6;\r\n");
      out.write("                chart.startDuration = 1;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tchart1 = new AmCharts.AmSerialChart();\r\n");
      out.write("                chart1.dataProvider = chartD;\r\n");
      out.write("                chart1.categoryField = \"name\";\r\n");
      out.write("                chart1.columnWidth = .6;\r\n");
      out.write("                chart1.startDuration = 1;\r\n");
      out.write("\r\n");
      out.write("                // AXES\r\n");
      out.write("                // Category\r\n");
      out.write("                var categoryAxis = chart.categoryAxis;\r\n");
      out.write("                categoryAxis.gridAlpha = 0.1;\r\n");
      out.write("                categoryAxis.axisAlpha = 0;\r\n");
      out.write("                categoryAxis.gridPosition = \"start\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar categoryAxis1 = chart1.categoryAxis;\r\n");
      out.write("                categoryAxis1.gridAlpha = 0.1;\r\n");
      out.write("                categoryAxis1.axisAlpha = 0;\r\n");
      out.write("                categoryAxis1.gridPosition = \"start\";\r\n");
      out.write("\r\n");
      out.write("                // Value\r\n");
      out.write("                var valueAxis = new AmCharts.ValueAxis();\r\n");
      out.write("                valueAxis.gridAlpha = 0.1;\r\n");
      out.write("                valueAxis.axisAlpha = 0;\r\n");
      out.write("                chart.addValueAxis(valueAxis);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar valueAxis1 = new AmCharts.ValueAxis();\r\n");
      out.write("                valueAxis1.gridAlpha = 0.1;\r\n");
      out.write("                valueAxis1.axisAlpha = 0;\r\n");
      out.write("                chart1.addValueAxis(valueAxis1);\r\n");
      out.write("\r\n");
      out.write("                // GRAPH\r\n");
      out.write("                var graph = new AmCharts.AmGraph();\r\n");
      out.write("                graph.valueField = \"close\";\r\n");
      out.write("                graph.openField = \"open\";\r\n");
      out.write("                graph.type = \"column\";\r\n");
      out.write("                graph.lineAlpha = 1;\r\n");
      out.write("                graph.lineColor = \"#BBBBBB\";\r\n");
      out.write("                graph.colorField = \"color\";\r\n");
      out.write("                graph.fillAlphas = 0.8;\r\n");
      out.write("                graph.balloonText = \"<span style='color:[[color]]'> [[category]] </span><br><span style='font-size:13px;'> <b>Rs.[[balloonValue]]</b></span>\";\r\n");
      out.write("                graph.labelText = \"Rs.[[balloonValue]]\";\r\n");
      out.write("                chart.addGraph(graph);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar graph1 = new AmCharts.AmGraph();\r\n");
      out.write("                graph1.valueField = \"close\";\r\n");
      out.write("                graph1.openField = \"open\";\r\n");
      out.write("                graph1.type = \"column\";\r\n");
      out.write("                graph1.lineAlpha = 1;\r\n");
      out.write("                graph1.lineColor = \"#BBBBBB\";\r\n");
      out.write("                graph1.colorField = \"color\";\r\n");
      out.write("                graph1.fillAlphas = 0.8;\r\n");
      out.write("                graph1.balloonText = \"<span style='color:[[color]]'> [[category]] </span><br><span style='font-size:13px;'> <b>Rs.[[balloonValue]]</b></span>\";\r\n");
      out.write("                graph1.labelText = \"Rs.[[balloonValue]]\";\r\n");
      out.write("                chart1.addGraph(graph1);\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                // WRITE\r\n");
      out.write("                chart.write(\"chartdiv\");\r\n");
      out.write("\t\t\t\tchart1.write(\"div\");\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"calcRoute()\">\r\n");
      out.write("\t<div class=\"card\" >\r\n");
      out.write("\t\t<input type=\"hidden\" value='");
      out.print(session.getAttribute("start") );
      out.write("'\r\n");
      out.write("\t\t\tid=\"start\"\r\n");
      out.write("\t\t> <input type=\"hidden\" value='");
      out.print(session.getAttribute("end") );
      out.write("'\r\n");
      out.write("\t\t\tid=\"end\"\r\n");
      out.write("\t\t>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1>CLEANSHEET</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right; padding-left: 5px\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<nav> <a href=\"Auto.jsp\">Auto</a> <br>\r\n");
      out.write("\t\t<a href=\"home.jsp\">Classic</a> <br>\r\n");
      out.write("\t\t<a href=\"Advanced.jsp\">Advanced</a> <br>\r\n");
      out.write("\t\t<a href=\"Param.jsp\">Control Panel</a> <br>\r\n");
      out.write("\t\t<a href=\"uploadFreight.jsp\">Upload Freight</a> <br>\r\n");
      out.write("\t\t<a href=\"uploadContract.jsp\">Upload Contract</a> <br>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section style=\"width: 45%\" >\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<h2 align=\"center\">Transport Cleansheet Output Summary </h2>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Origin City :</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(session.getAttribute("start") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Destination City :</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(session.getAttribute("end") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
DecimalFormat df = new DecimalFormat("#.##");
						Float dist=(Float)session.getAttribute("distance");
      out.write(" Distance Is\r\n");
      out.write("\t\t\t\t\t\t\t(In KM) :\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(df.format(dist) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Capacity (In Tons) :</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(session.getAttribute("cap") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\tFixed Cost/Month/Km<div id=\"chartdiv\" style=\"width:500px; height: 250px;\"></div>\r\n");
      out.write("\t\t\t\tVariable Cost/Km<div id=\"div\" style=\"width:500px; height: 250px;\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<div id=\"map_canvas\" class=\"right\" style=\"height: 66%; width: 35%\"></div>\r\n");
      out.write("\t\t<footer style=\"position:  relative;\"> Copyright &copy McKinsey &\r\n");
      out.write("\t\tCompany </footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
