/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-10-20 04:09:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.DB.connection.Connect;

public final class variable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 	 if(null==((String) session.getAttribute("empid")) )
        {
            response.sendRedirect("index.jsp");
            return;
        }
	//if(null == request.getSession(false))
	//{
	//response.sendRedirect("index.jsp");
	//}
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/homestyle.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Variable Cost</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function myFunction() {\r\n");
      out.write("    location.reload();\r\n");
      out.write("}\r\n");
      out.write("function clickadd()\r\n");
      out.write("{\r\n");
      out.write("document.getElementById('add').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('del').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('modify').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('refresh').style.visibility = 'hidden';\r\n");
      out.write("document.getElementById('1').style.visibility = 'visible';\r\n");
      out.write("document.getElementById('2').style.visibility = 'visible';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/styles.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
String name = request.getParameter( "name" );
	 
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<h1>CLEANSHEET</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tHello,\r\n");
      out.write("\t\t\t");
      out.print( session.getAttribute( "name" ) );
      out.write("\r\n");
      out.write("\t\t\t<a style=\"float: right;\" href=\"Logout\">Logout</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<nav> <a href=\"Auto.jsp\">Auto</a> <br>\r\n");
      out.write("\t\t<a href=\"home.jsp\">Classic</a> <br>\r\n");
      out.write("\t\t<a href=\"Advanced.jsp\">Advanced</a> <br>\r\n");
      out.write("\t\t<a href=\"Param.jsp\">Control Panel</a>\r\n");
      out.write("\t\t<ul type=\"circle\" compact=\"true\">\r\n");
      out.write("\t\t\t<li><a href=\"Capex.jsp\"> Capex</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"fixed.jsp\"> Fixed Cost</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"variable.jsp\"> Variable Cost</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"trip.jsp\"> Trip Matrix</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a href=\"uploadFreight.jsp\">Upload Freight</a> <br>\r\n");
      out.write("\t\t<a href=\"uploadContract.jsp\">Upload Contract</a> <br>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section style=\"width:79%\">\r\n");
      out.write("\t\t<div class=\"login-card\">\r\n");
      out.write("\t\t\t<h2 align=\"center\">Control Panel</h2>\r\n");
      out.write("\t\t\t<form action=\"Param\" method=\"post\">\r\n");
      out.write("\t\t\t\t<h2 style=\"\" align=\"center\">Variable Cost</h2>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Truck Type</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Tyre life (Km)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Tyre life (Retredded tyre) (Km)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Tyre Cost (INR)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Tyre Cost (Retredded tyre) (INR)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>No. of tyres</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Diesel Cost</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Diesel Milage Km/L</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Diesel Mileage (With Load) Km/L</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Toll per km</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Route expenses per km</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Maintanence cost per km</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

			int empid=Integer.parseInt((String)session.getAttribute("empid"));
		 	String sql = "select * from `routeparam`  where `Emp_id`="+empid+" order by `capacity`";
			 
				try{ 
							 Connection con = Connect.getconnection();
							 PreparedStatement ps=con.prepareStatement(sql);					 		 
					 		 ResultSet rs = ps.executeQuery();
					               while( rs.next() )
					 		 {
							 	
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" value='");
      out.print(rs.getString("capacity"));
      out.write("'></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

					 		}
			
					            	
				}
				catch(Exception e){
					e.printStackTrace();
					RequestDispatcher ReqDis = request.getRequestDispatcher("error.jsp");
				ReqDis.forward(request, response);
				}
		
      out.write("\t<tr id=1 style=\"visibility: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"truckType\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"costoftruck\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"residual\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"loan\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"emi\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"roi\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"flatroi\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" required></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"insurance\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr id=\"2\" style=\"visibility: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" value='");
      out.print(session.getAttribute("empid"));
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"empid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t> <input type=\"submit\" name=\"submit\" value=\"Submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login login-submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><center>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction()\" value=\"Cancel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login login-submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\"><input type=\"button\" value=\"Add\" name=\"add\" id=\"add\" class=\"login login-submit\" onclick=\"clickadd()\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td colspan=\"1\"></td>\r\n");
      out.write("\t\t<td colspan=\"2\"><input type=\"button\" value=\"Modify\" name=\"modify\" id=\"modify\" class=\"login login-submit\" onclick=\"\"></td>\r\n");
      out.write("\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t<td colspan=\"2\"><input type=\"button\" value=\"Delete\" name=\"del\" id=\"del\" class=\"login login-submit\" onclick=\"\"></td>\r\n");
      out.write("\t\t<td colspan=\"1\"></td>\r\n");
      out.write("\t\t<td colspan=\"2\"><input type=\"button\" value=\"Refresh\" name=\"refresh\" id=\"refresh\" class=\"login login-submit\" onclick=\"myFunction()\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer style=\"position:  relative;\"> Copyright © McKinsey &\r\n");
      out.write("\t\tCompany </footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
